name: WooSeller
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  image_picker: ^0.8.0+4
  flutter_html: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - android/app/src/main/res/
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/
